# Generated by Django 5.2.1 on 2025-06-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cls',
            field=models.CharField(default=' ', max_length=60),
        ),
    ]
